# Generated by Django 5.1.6 on 2025-04-08 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0002_remove_user_eamil_alter_user_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_view', 'Peut voir le contenu'), ('can_edit', 'Peut modifier le contenu')]},
        ),
    ]
