# Generated by Django 5.1.6 on 2025-04-10 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0003_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_view_user', 'Peut lire les utilisateurs'), ('can_edit_user', 'Peut modifier les utilisateurs')]},
        ),
    ]
