# Generated by Django 5.1.6 on 2025-04-10 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0005_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_add_user', 'Peut ajouter un utilisateur'), ('can_change_user', 'Peut modifier un utilisateur'), ('can_delete_user', 'Peut supprimer un utilisateur'), ('can_view_user', 'Peut voir un utilisateur')]},
        ),
    ]
