# Generated by Django 5.2 on 2025-04-12 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0009_customgroup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomGroup',
        ),
    ]
