# Generated by Django 5.2 on 2025-04-12 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0012_customgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='customgroup',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owned_groups', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
