# Generated by Django 5.2 on 2025-04-13 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0013_customgroup_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomGroup',
        ),
    ]
