# Generated by Django 5.2 on 2025-04-13 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0015_extendedgroup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtendedGroup',
        ),
    ]
