# Generated by Django 5.2 on 2025-04-13 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0017_extendedgroup_user_extended_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='extended_groups',
        ),
        migrations.DeleteModel(
            name='ExtendedGroup',
        ),
    ]
