# Generated by Django 5.2 on 2025-07-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0018_remove_user_extended_groups_delete_extendedgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
