# Generated by Django 5.1.6 on 2025-04-08 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant', models.IntegerField(unique=True)),
                ('type_animal', models.CharField(choices=[('boeuf', 'Bœuf'), ('ane', 'Âne'), ('mouton', 'Mouton'), ('cheval', 'Cheval'), ('chevre', 'Chèvre')], max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ZoneSecurite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('rayon', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corps_message', models.TextField()),
                ('date_heure', models.DateTimeField(auto_now_add=True)),
                ('identifiant_capteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='capteurs.capteur', to_field='identifiant')),
            ],
        ),
        migrations.AddField(
            model_name='capteur',
            name='zone_securite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='capteurs.zonesecurite'),
        ),
    ]
