# Generated by Django 5.2 on 2025-04-29 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_animal', models.CharField(choices=[('boeuf', '● Boeuf'), ('ane', '● Âne'), ('mouton', '● Mouton'), ('cheval', '● Cheval'), ('chevre', '● Chèvre')], max_length=20, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='animaux/')),
            ],
        ),
        migrations.CreateModel(
            name='ZoneSecurite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('forme', models.CharField(choices=[('cercle', 'Cercle'), ('triangle', 'Triangle'), ('carre', 'Carré'), ('rectangle', 'Rectangle'), ('polygon', 'Polygone')], default='cercle', max_length=10)),
                ('is_pred', models.BooleanField(default=True)),
                ('is_zone', models.BooleanField(default=True)),
                ('active_securite', models.BooleanField(default=False)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('rayon', models.FloatField(blank=True, null=True)),
                ('coin1_lat', models.FloatField(blank=True, null=True)),
                ('coin1_lon', models.FloatField(blank=True, null=True)),
                ('coin2_lat', models.FloatField(blank=True, null=True)),
                ('coin2_lon', models.FloatField(blank=True, null=True)),
                ('coin3_lat', models.FloatField(blank=True, null=True)),
                ('coin3_lon', models.FloatField(blank=True, null=True)),
                ('coin4_lat', models.FloatField(blank=True, null=True)),
                ('coin4_lon', models.FloatField(blank=True, null=True)),
                ('coins', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corps_message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('date_heure', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='capteurs.zonesecurite')),
            ],
        ),
        migrations.CreateModel(
            name='Capteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant', models.IntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('is_zone', models.BooleanField(default=True)),
                ('actif', models.BooleanField(default=True)),
                ('type_animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capteurs.animal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capteurs', to=settings.AUTH_USER_MODEL)),
                ('zone_securite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='capteurs.zonesecurite')),
            ],
        ),
        migrations.AddConstraint(
            model_name='zonesecurite',
            constraint=models.UniqueConstraint(fields=('user', 'nom'), name='unique_nom_par_utilisateur'),
        ),
    ]
