# Generated by Django 5.2 on 2025-04-29 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capteurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='type_animal',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
