# Generated by Django 5.2 on 2025-04-30 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capteurs', '0002_alter_animal_type_animal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='capteurs/'),
        ),
    ]
