# Generated by Django 5.2 on 2025-04-12 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capteurs', '0003_capteur_user_zonesecurite_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='capteur',
            name='identifiant',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='capteur',
            name='type_animal',
            field=models.CharField(choices=[('boeuf', 'Boeuf'), ('ane', 'Âne'), ('mouton', 'Mouton'), ('cheval', 'Cheval'), ('chevre', 'Chèvre')], max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='identifiant_capteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='capteurs.capteur'),
        ),
        migrations.AlterUniqueTogether(
            name='capteur',
            unique_together={('user', 'identifiant')},
        ),
    ]
