# Generated by Django 5.2 on 2025-05-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capteurs', '0003_alter_animal_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capteur',
            name='identifiant',
            field=models.IntegerField(unique=True),
        ),
    ]
