# Generated by Django 5.2 on 2025-05-07 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capteurs', '0004_alter_capteur_identifiant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capteur',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='capteur',
            name='longitude',
        ),
    ]
