# Generated by Django 5.2 on 2025-04-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capteurs', '0005_message_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='zonesecurite',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='zonesecurite',
            name='nom',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
