# Generated by Django 5.2 on 2025-05-29 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capteurs', '0005_remove_capteur_latitude_remove_capteur_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capteur',
            name='type_animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='capteurs.animal'),
        ),
    ]
