# Generated by Django 5.2 on 2025-04-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capteurs', '0006_zonesecurite_description_zonesecurite_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zonesecurite',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zonesecurite',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zonesecurite',
            name='rayon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
