# Generated by Django 5.2 on 2025-06-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capteurs', '0006_alter_capteur_type_animal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zonesecurite',
            name='nom',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
