# Generated by Django 5.2 on 2025-04-22 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capteurs', '0007_alter_zonesecurite_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zonesecurite',
            name='coin1_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zonesecurite',
            name='coin1_lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zonesecurite',
            name='coin2_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zonesecurite',
            name='coin2_lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zonesecurite',
            name='coin3_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zonesecurite',
            name='coin3_lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zonesecurite',
            name='coins',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zonesecurite',
            name='forme',
            field=models.CharField(choices=[('cercle', 'Cercle'), ('triangle', 'Triangle'), ('carre', 'Carré'), ('polygon', 'Polygone')], default='cercle', max_length=10),
        ),
    ]
