# Generated by Django 5.2 on 2025-06-09 09:53

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capteurs', '0007_alter_zonesecurite_nom'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='zonesecurite',
            name='unique_nom_par_utilisateur',
        ),
        migrations.AlterField(
            model_name='zonesecurite',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='zonesecurite',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nom'), name='unique_nom_insensible_casse'),
        ),
    ]
