# Generated by Django 5.2 on 2025-04-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capteurs', '0008_zonesecurite_coin1_lat_zonesecurite_coin1_lon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zonesecurite',
            name='coin4_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zonesecurite',
            name='coin4_lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zonesecurite',
            name='forme',
            field=models.CharField(choices=[('cercle', 'Cercle'), ('triangle', 'Triangle'), ('carre', 'Carré'), ('rectangle', 'Rectangle'), ('polygon', 'Polygone')], default='cercle', max_length=10),
        ),
    ]
