# Generated by Django 5.2 on 2025-04-23 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capteurs', '0009_zonesecurite_coin4_lat_zonesecurite_coin4_lon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='identifiant_capteur',
        ),
        migrations.AddField(
            model_name='message',
            name='zone',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='capteurs.zonesecurite'),
            preserve_default=False,
        ),
    ]
