# Generated by Django 5.2 on 2025-04-24 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capteurs', '0010_remove_message_identifiant_capteur_message_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='capteur',
            name='is_zone',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='capteur',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zonesecurite',
            name='is_zone',
            field=models.BooleanField(default=True),
        ),
    ]
