# Generated by Django 5.2 on 2025-04-24 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capteurs', '0011_capteur_is_zone_capteur_last_seen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='capteur',
            name='is_zonepre',
            field=models.BooleanField(default=True),
        ),
    ]
