# Generated by Django 5.2 on 2025-04-24 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capteurs', '0012_capteur_is_zonepre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='capteur',
            old_name='is_zonepre',
            new_name='is_pred',
        ),
    ]
