# Generated by Django 5.2 on 2025-04-24 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capteurs', '0013_rename_is_zonepre_capteur_is_pred'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capteur',
            name='is_pred',
        ),
        migrations.AddField(
            model_name='zonesecurite',
            name='is_pred',
            field=models.BooleanField(default=True),
        ),
    ]
