# Generated by Django 5.2 on 2025-04-26 15:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capteurs', '0014_remove_capteur_is_pred_zonesecurite_is_pred'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='capteur',
            name='type_animal',
            field=models.CharField(choices=[('boeuf', '● Boeuf'), ('ane', '● Âne'), ('mouton', '● Mouton'), ('cheval', '● Cheval'), ('chevre', '● Chèvre')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='zonesecurite',
            constraint=models.UniqueConstraint(fields=('user', 'nom'), name='unique_nom_par_utilisateur'),
        ),
    ]
