# Generated by Django 5.2 on 2025-04-27 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capteurs', '0015_alter_capteur_type_animal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capteur',
            name='zone_securite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='capteurs.zonesecurite'),
        ),
    ]
