# Generated by Django 5.2 on 2025-04-27 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capteurs', '0016_alter_capteur_zone_securite'),
    ]

    operations = [
        migrations.AddField(
            model_name='zonesecurite',
            name='active_securite',
            field=models.BooleanField(default=False),
        ),
    ]
